dataloaders:
  _target_: biomass.dataloaders.RxRx1WildsCellDataloaders
  eval_splits: 
    - val
    - iid_val
  train_transform:
    _target_: biomass.transforms.Compose
    transforms:
    - _target_: biomass.transforms.RandomRotate
    - _target_: biomass.transforms.RandomHorizontalFlip
    - _target_: biomass.transforms.RandomResizedCrop
      size: [48, 48]
    - _target_: biomass.transforms.GaussianBlur
      kernel_size: 25
      sigma: [0.1, 0.5]
    - _target_: biomass.transforms.ToTensor
    - _target_: biomass.transforms.Standardize
      dim: [-2, -1]
  eval_transform:
    _target_: biomass.transforms.Compose
    transforms:
    - _target_: biomass.transforms.ToTensor
    - _target_: biomass.transforms.Standardize
      dim: [-2, -1]
  img_dir: rxrx1_cells
  summary_file: misc/summary_rxrx1.csv
  mode: random_single
  sampler: random
  num_img: 2
  num_plates_per_batch: 1
  num_plate_parts: 1
  use_one_site: False
  # include_labels: True
  # metadata_file: data/rxrx1_v1.0/metadata.csv
model:
  _target_: biomass.models.ContrastiveLearner
  encoder:
    _target_: biomass.models.TorchVisionEncoder
    name: resnet50
    classifier_key: fc
    pretrained: True
  classifier:
    _target_: biomass.models.Linear
    in_features: 2048
    out_features: 1139
    bias: True
  proj_nonlinear: True
  proj_in: 2048
  proj_out: 128
device: cuda
learning_rate: 1e-3
weight_decay: 0
num_epochs: 500
num_warmup_epochs: 50
train_batch_size: 300
eval_batch_size: 300
temperature: 0.05
num_views: 2
save_model: True
no_eval: False
bn_by_plate: False
clip_grad_norm: ~
model_path: ~
store_prev_batch: False
use_domain_batch_norm: False