dataloaders:
  _target_: biomass.dataloaders.RxRx1Dataloaders
  eval_splits: 
    - val
  train_transform:
    _target_: biomass.transforms.MultiView
    n_views: 2
    transform:
      _target_: biomass.transforms.Compose
      transforms:
      - _target_: biomass.transforms.RandomRotate
      - _target_: biomass.transforms.RandomHorizontalFlip
      - _target_: biomass.transforms.RandomResizedCrop
        size: [256, 256]
        scale: [0.2, 1.0]
      - _target_: biomass.transforms.RandomApply
        transforms:
          - _target_: biomass.transforms.ColorJitter
            brightness: 0.4
            contrast: 0.4
            saturation: 0.4
            hue: 0.1
        p: 0.8
      - _target_: biomass.transforms.RandomGrayscale
        p: 0.2
      # - _target_: biomass.transforms.GaussianBlur
      #   kernel_size: 25
      #   sigma: [0.1, 2.0]
      - _target_: biomass.transforms.ToTensor
      - _target_: biomass.transforms.Standardize
        dim: [-2, -1]
model:
  _target_: biomass.models.SimSiam
  encoder:
    _target_: biomass.models.TorchVisionEncoder
    name: resnet50
    classifier_key: fc
    zero_init_residual: True
  dim: 2048
  pred_dim: 512
device: cuda
learning_rate: 0.05
momentum: 0.9
weight_decay: 1e-5
num_epochs: 90
train_batch_size: 64
eval_batch_size: 768
knn_neighbors:
  - 10
  - 50
  - 200
save_model: True