dataloaders:
  _target_: biomass.dataloaders.RxRx1WildsCellDataloaders
  eval_splits: 
    - val
    - iid_val
  train_transform:
    _target_: biomass.transforms.Compose
    transforms:
    - _target_: biomass.transforms.RandomRotate
    - _target_: biomass.transforms.RandomHorizontalFlip
    - _target_: biomass.transforms.ToTensor
    - _target_: biomass.transforms.Standardize
      dim: [-2, -1]
  eval_transform:
    _target_: biomass.transforms.Compose
    transforms:
    - _target_: biomass.transforms.ToTensor
    - _target_: biomass.transforms.Standardize
      dim: [-2, -1]
  img_dir: ../rxrx1_cells
  summary_file: ../summary_rxrx1.csv
  mode: all
  sampler: random
  include_labels: True
  metadata_file: data/rxrx1_v1.0/metadata.csv
  use_one_site: False
model:
  _target_: biomass.models.ContrastiveLearner
  encoder:
    _target_: biomass.models.TorchVisionEncoder
    name: resnet50
    classifier_key: fc
    pretrained: False
  classifier:
    _target_: biomass.models.Linear
    in_features: 2048
    out_features: 1139
    bias: True
  proj_nonlinear: True
  proj_in: 2048
  proj_out: 128
model_path: checkpoints/simclr_2022_09_02_15_11_36.pt
sup_model_path: ~
device: cuda
optimizer: adam
learning_rate: 1e-1
weight_decay: 0
num_epochs: 30
train_batch_size: 300
eval_batch_size: 300
pooler: 
  _target_: biomass.poolers.MeanPooler
  # _target_: biomass.poolers.AttentionPooler
  # dims: 
  # - 2048
  # - 512
in_features: 2048
out_features: 1139
clip_grad_norm: 5
save_model: True
use_projs: False
normalize: True
model_train_mode: False
normalize_img_feats: False
save_key: val
use_domain_batch_norm: False
use_scheduler: True