dataloaders:
  _target_: biomass.dataloaders.RxRx1WildsCellDataloaders
  eval_splits: 
    - val
    - iid_val
  train_transform:
    _target_: biomass.transforms.Compose
    transforms:
    - _target_: biomass.transforms.RandomRotate
    - _target_: biomass.transforms.RandomHorizontalFlip
    - _target_: biomass.transforms.ToTensor
    - _target_: biomass.transforms.Standardize
      dim: [-2, -1]
  eval_transform:
    _target_: biomass.transforms.Compose
    transforms:
    - _target_: biomass.transforms.ToTensor
    - _target_: biomass.transforms.Standardize
      dim: [-2, -1]
  img_dir: ../rxrx1_cells
  summary_file: ../summary_rxrx1.csv
  mode: all
  sampler: random
  include_labels: True
  metadata_file: data/rxrx1_v1.0/metadata.csv
model:
  _target_: biomass.models.ContrastiveLearner
  encoder:
    _target_: biomass.models.TorchVisionEncoder
    name: resnet50
    classifier_key: fc
    pretrained: False
  classifier:
    _target_: biomass.models.Linear
    in_features: 2048
    out_features: 1139
    bias: True
  proj_nonlinear: True
  proj_in: 2048
  proj_out: 128
model_path: checkpoints/simclr_2022_07_26_16_44_30.pt
device: cuda
learning_rate: 1e-2
weight_decay: 0
num_epochs: 30
train_batch_size: 256
eval_batch_size: 256
in_features: 2048
out_features: 1139
clip_grad_norm: 5
save_model: False
use_projs: False
normalize: True