dataset:
  _target_: biomass.datasets.CellOutOfSampleDataset
  path: ${hydra:runtime.cwd}/COOS7_v1.1_training.hdf5
  random_flips: True
model:
  _target_: biomass.models.PairedCellInpainter
learning_rate: 1e-4
num_epochs: 100
batch_size: 128
device: cuda
save_model: True